version: '2.4'
services:
  hello-edge:
    image: hello-edge:0.0.20
    build: .
    ports:
      - '1234:80'
    mem_limit: 200mb
    restart: always
    volumes:
      - './html/:/usr/share/nginx/html'
