name: CI
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main]

jobs:
  build: 
    runs-on: self-hosted
    container:
      image: halamap26/repopublisher:1.3.6
      options: --privileged
      credentials:
        username: ${{secrets.DHUB_USER}}
        password: ${{secrets.DHUB_PSWRD}}
        
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
     - uses: actions/checkout@v2
     - name: build and save 
       run: |
         cd app
         mkdir artifacts
         cp docker-compose.yml ./artifacts
         cp Dockerfile ./artifacts
         cp -R ./html ./artifacts
         cd artifacts
         ls
         docker-compose build 
         docker save -o docker-images.tar $(docker-compose config | awk '{if ($1 == "image:") print $2;}')
     - uses: actions/upload-artifact@master
       with:
          name: my-artifact
          path: app/artifacts

  upload:
    runs-on: self-hosted
    needs: [build]
    container:
      image: halamap26/repopublisher:1.3.6
      options: --privileged
      credentials:
        username: ${{secrets.DHUB_USER}}
        password: ${{secrets.DHUB_PSWRD}}
        
    services: 
     docker: 
        image: docker:18.09-dind
        options: --privileged

        
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/download-artifact@master
        with:
          name: my-artifact
          path: app/artifacts
      - name: Loading docker images
        run: |
          cd  app/artifacts/
          docker --host tcp://docker:2375 load --input docker-images.tar
      - name: Uploading app to IEM
        run: |
          ie-app-publisher-linux -V
          cp -RT app /app/src/workspace
          cd /app/src/workspace
          ie-app-publisher-linux de c -u http://docker:2375
          export IE_SKIP_CERTIFICATE=true
          ie-app-publisher-linux em li -u ${{secrets.IEM_URL}} -e ${{secrets.USER_NAME}} -p ${{secrets.PSWD}}
          pwd
          version=$(ie-app-publisher-linux em app dt -a ${{secrets.APP_ID}} -p | \
            python3 -c "import sys, json; print(json.load(sys.stdin)['versions'][0]['versionNumber'])")
          
          echo $version
          if [ -z "$version" ]
          then
              version_new=0.0.1
              echo 'New application created with version: '$version_new
          else
              echo 'old Version: '$version
              version_new=$(echo $version | awk -F. -v OFS=. 'NF==1{print ++$NF}; NF>1{if(length($NF+1)>length($NF))$(NF-1)++; $NF=sprintf("%0*d", length($NF), ($NF+1)%(10^length($NF))); print}')
              echo 'new Version: '$version_new
          fi
          ie-app-publisher-linux em app cuv -a ${{secrets.APP_ID}} -v $version_new -y ./docker-compose.prod.yml -n '{"hello-edge":[{"name":"hello-edge","protocol":"HTTP","port":"80","headers":"","rewriteTarget":"/"}]}' -s 'hello-edge' -t 'FromBoxReverseProxy' -u "hello-edge" -r "/"
          ie-app-publisher-linux em app uuv -a ${{secrets.APP_ID}} -v $version_new
  deploy: 
    runs-on: self-hosted
    needs: [upload]
    container:
      image: python:3
      options: --privileged

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
     - uses: actions/checkout@v2
     - name: deploy
       env:
        IE_URL: ${{secrets.IEM_URL}}
        IE_APPS: ${{secrets.IE_APPS}}
        IE_PASSWORD: ${{secrets.PSWD}}
        IE_USER: ${{secrets.USER_NAME}}
        APP_ID: ${{secrets.APP_ID}}
       run: |
          install $GITHUB_WORKSPACE/publisher/ie-app-publisher-linux /usr/bin/
          export IE_SKIP_CERTIFICATE=true
          ie-app-publisher-linux em li -u ${{secrets.IEM_URL}} -e ${{secrets.USER_NAME}} -p ${{secrets.PSWD}}
          pip install requests-toolbelt
          appVersionId=$(ie-app-publisher-linux em app dt -a ${{secrets.APP_ID}} -p | \
            python3 -c "import sys, json; print(json.load(sys.stdin)['versions'][0]['versionId'])")
          echo $appVersionId
          python -u ./script/api_handler.py pipeline --devices device2,devicepavel --appVersionID $appVersionId          